apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nodejs-oidytyux
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-oidytyux 
  name: nodejs-oidytyux
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-oidytyux
    weight: 100 
